// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtraaCjHhZTl5aE2GJfPk6Ss3SCY6gWHo',
    appId: '1:528642462565:web:401b9e206c1b81df15878c',
    messagingSenderId: '528642462565',
    projectId: 'projeto-cm-43e67',
    authDomain: 'projeto-cm-43e67.firebaseapp.com',
    storageBucket: 'projeto-cm-43e67.firebasestorage.app',
    measurementId: 'G-TXX5QD4RB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDow7id_dgrn7ocy-hhkNUhtXOffnn9d48',
    appId: '1:528642462565:android:1c43beb9cb2585ce15878c',
    messagingSenderId: '528642462565',
    projectId: 'projeto-cm-43e67',
    storageBucket: 'projeto-cm-43e67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPPBMtUx44ypuadAMGzb5ime9M2VWhRuU',
    appId: '1:528642462565:ios:f38609eb8162891515878c',
    messagingSenderId: '528642462565',
    projectId: 'projeto-cm-43e67',
    storageBucket: 'projeto-cm-43e67.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPPBMtUx44ypuadAMGzb5ime9M2VWhRuU',
    appId: '1:528642462565:ios:f38609eb8162891515878c',
    messagingSenderId: '528642462565',
    projectId: 'projeto-cm-43e67',
    storageBucket: 'projeto-cm-43e67.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtraaCjHhZTl5aE2GJfPk6Ss3SCY6gWHo',
    appId: '1:528642462565:web:cd7848ff6a349d9815878c',
    messagingSenderId: '528642462565',
    projectId: 'projeto-cm-43e67',
    authDomain: 'projeto-cm-43e67.firebaseapp.com',
    storageBucket: 'projeto-cm-43e67.firebasestorage.app',
    measurementId: 'G-B70KVWB077',
  );

}